# Area512 built-in type declaration.

class GPIO
  # Check if GPIO pin is HIGH
  def high?: () -> bool

  # Check if GPIO pin is LOW
  def low?: () -> bool

  # Set to open drain output mode
  def open_drain: (Integer flags) -> Integer

  # Read GPIO pin state
  def read: () -> Integer

  # Write value to GPIO pin
  def write: (Integer value) -> Integer

  # Check if specified pin is HIGH
  def self.high_at?: ((Integer | String | Symbol) pin) -> bool

  # Check if specified pin is LOW
  def self.low_at?: ((Integer | String | Symbol) pin) -> bool

  # Create GPIO object
  def self.new: ((Integer | String | Symbol) pin, Integer flags, ?Integer alt_function) -> GPIO

  # Set specified pin to open drain output mode
  def self.open_drain_at: ((Integer | String | Symbol) pin) -> Integer

  # Set specified pin to pull-down
  def self.pull_down_at: ((Integer | String | Symbol) pin) -> Integer

  # Set specified pin to pull-up
  def self.pull_up_at: ((Integer | String | Symbol) pin) -> Integer

  # Read specified pin state
  def self.read_at: ((Integer | String | Symbol) pin) -> Integer

  # Set input/output direction of specified pin
  def self.set_dir_at: ((Integer | String | Symbol) pin, Integer flags) -> Integer

  # Set function of specified pin
  def self.set_function_at: ((Integer | String | Symbol) pin, Integer alt_function) -> Integer

  # Write value to specified pin
  def self.write_at: ((Integer | String | Symbol) pin, Integer value) -> Integer

end
